### ISSUE TITLE
SearchRange still O(n) in the worst case

### ISSUE THREAD

**Issue by MazenAmria** [Mo7ammadAbuSafat/foothill-trainee#11]
Almost correct, but suppose that you have the following array:
```python
[5, 5, 5, 5, ..., 5]
```
and you want to find the range of 5, it would be `O(n)` due to the following for loop.

https://github.com/Mo7ammadAbuSafat/foothill-trainee/blob/6330ebc2a38f19e4866f86bfa1d72f9f903c2df7/LeetCode/SearchRangeClass.cs#L33

You've got the idea of the binary search which is correct, but you need to implement it right to get the range correctly.
Check the lower and upper bounds.

https://cp-algorithms.com/num_methods/binary_search.html#lower-bound-and-upper-bound

**Comment by Mo7ammadAbuSafat** [comment]
https://github.com/Mo7ammadAbuSafat/foothill-trainee/blob/main/LeetCode/SearchRangeClass.cs
@MazenAmria 
its done
