### ISSUE TITLE
Linked List Cycle II: O(1) Space Complexity

### ISSUE THREAD

**Issue by MazenAmria** [Mo7ammadAbuSafat/foothill-trainee#5]
In your solution you're using a set to store the path and then check if it's contains the next node, this have a worst case space complexity of O(n). Can you modify this question to reduce the space complexity to O(1)?

https://github.com/Mo7ammadAbuSafat/foothill-trainee/blob/a683b27843e7728b20e696f9c96b075a3a9ebabb/LeetCode/LinkedListCycle.cs

**Comment by Mo7ammadAbuSafat** [comment]
I have updated the solution
@MazenAmria

**Comment by MazenAmria** [comment]
@Mo7ammadAbuSafat https://algo.monster/problems/linked_list_cycle

**Comment by Mo7ammadAbuSafat** [comment]
@MazenAmria 
in this file https://github.com/Mo7ammadAbuSafat/foothill-trainee/blob/main/LeetCode/LinkedListCycle.cs
you can see in method "DetectCycle2" that I have been applied this algorithm 
(this for check if there is a cycle or not but question need to return the node also)
